(** This module allows to print messages to user. *)

(** Severity levels from les serious to most serious *)
type levels = Trace | Debug | Info | Warn | Error | Fatal

(** Keeps a log of all messages generated during execution *)
type log

(** Name says it all *)
val empty : log

(** [add_message message level log] inserts [message] in [log] with severity [level] *)
val add_message : string -> levels -> log -> log

(** Messages added to the log generated by [new_level label log] will start with [label] *)
val new_level : string -> log -> log

(** Restores the previous log label *)
val level_back : log -> log

(** Prints all messages in log *)
val print_all : log -> levels -> unit